### ISSUE TITLE
代码生成器，生成排序字段时的BUG

### ISSUE THREAD

**Issue by longyq1988** [izhaorui/ZrAdmin.NET#13]
代码生成器，生成排序字段时，写入的不是字段名而是属性名称；比如字段名：T_CreateTime对于属性名称TCreateTime，生成出来的sql：order by TCreateTime .......

**Comment by izhaorui** [comment]
贴下具体sql

**Comment by longyq1988** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "izhaorui/ZrAdmin.NET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月14日(星期二) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [izhaorui/ZrAdmin.NET] 代码生成器，生成排序字段时的BUG (Issue #13)





 
贴下具体sql

**Comment by izhaorui** [comment]
你这发 的什么
