### ISSUE TITLE
前端跑不起来

### ISSUE THREAD

**Issue by yf2468** [izhaorui/ZrAdmin.NET#14]
PS C:\Users\vitagreen\Desktop\2022\ZrAdmin.NET-main\ZR.Vue> pnpm dev

> zradmin@ dev C:\Users\vitagreen\Desktop\2022\ZrAdmin.NET-main\ZR.Vue
> vue-cli-service serve

'vue-cli-service' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
 ELIFECYCLE  Command failed with exit code 1.
PS C:\Users\vitagreen\Desktop\2022\ZrAdmin.NET-main\ZR.Vue>

**Comment by izhaorui** [comment]
npm 学习下

**Comment by izhaorui** [comment]
环境要求是文档里面写的吗

**Comment by yf2468** [comment]
我是在github中下载源代码，然后在vs code里面打开运行的。文档中没有在vs里面打开的说明，后台则是正常的。

**Comment by yf2468** [comment]
可以了，谢谢，支付宝请你喝杯咖啡。

**Comment by izhaorui** [comment]
感谢
